### ISSUE TITLE
Question: Fanuc Robot Connection

### ISSUE THREAD

**Issue by kdorsel** [dmroeder/pylogix#126]
### Preflight checks

- [x] Have you tried the examples?
- [x] Have you tried [pylogix-tester](https://github.com/kodaman2/pylogix-tester)?
- [x] Have you read previous issues?

## Type of issue

- [ ] Bug
- [ ] Feature Request
- [x] Question
- [ ] Other

## Description of issue
Has anyone had any success connection to Fanuc robots with this library? I can connect to it and the `GetDeviceProperties()` successfully returns, but no other functions work and all give me `Forward open failed` or `Path segment error`.

Does anyone know of special module number or sequence to get it started up and working? Normally I would configure the config instance, input and output connection points like so. How would these translate to this library?

![Screenshot from 2020-04-20 18-16-06](https://user-images.githubusercontent.com/2569415/79804975-2248f980-8333-11ea-8c84-82b18a8126e5.png)

## Code
```
from pylogix import PLC

with PLC('192.168.0.10') as comm:
    print(comm.GetDeviceProperties())
    print(comm.GetProgramsList())
    print(comm.GetTagList())
    print(comm.GetPLCTime())
    for ii in range(0,100):
        print(comm.GetModuleProperties(ii))
```
Results:
```
None 0 0 0.0.0.0 356 Fanuc Robotics America 12 None 4 3.1 52 0xe4490e0e 18 FANUC Robot R30iB+ 43 Success
None None Forward open failed
None None Forward open failed
None None Forward open failed
None None None None None None None None None None None None None None None Path segment error
etc
```

## Versions
- pylogix: 0.6.6
- python: 3.8.2
- OS: Ubuntu 18.04

**Comment by kodaman2** [comment]
@kdorsel this library is only intended to communicate with Rockwell plc's compactlogix/controllogix. The only reason why you get information with GetDeviceProperties is because there's a list of manufacturers in [lgxDevice]( https://github.com/dmroeder/pylogix/blob/master/pylogix/lgxDevice.py#L455) this is just to identify devices on the same LAN. Pylogix can't access any other information or communicate with Fanuc Robots.
