### ISSUE TITLE
Path Segment Error

### ISSUE THREAD

**Issue by rprovosty** [dmroeder/pylogix#39]
When running a test script for reading a tag I encounter the 'Path Segment Error.'

test = PLC()
test.ProcessorSlot = 1
test.IPAddress = '192.168.1.1'
value = test.Read('para_scale')
print(value)
test.close()

I know that the PLC can be seen by using the .Discover() method. It outputs:

with PLC() as comm:
    devices = comm.Discover()
    for device in devices:
        print(device.IPAddress)
        print (' Product Code:'+ device.ProductName + ' ' +str(device.ProductCode))

192.168.1.1
 Product Code:1756-L82E/B 165

I am very excited to use this library.
Thank you

**Comment by dmroeder** [comment]
Path segment error suggest that you have the tag name wrong, or it cannot find the tag name in the PLC.  The most likely cause is that the tag is created in the program scope rather than the controller scope.

If it was in fact created as a program scoped tag, you can get to it by specifying that it's program scoped and providing the program name.  Let's say that you a program called Line1 and your tag is part of that tag scope.  You would read:

`value = test.Read("Program:Line1.para_scale")`

If that is not it, the it could be that your L82E is not in slot 0 of the chassis.  If that is the case, you have to specify which slot it is in prior to your read:

`test.ProcessorSlot = 1 # processor is in slot 1`
